--- 
apiVersion: v1
kind: elk
labels: 
  apache: ElasticSearch Kibana
metadata: 
  name: app
  annotations:
    title: ElasticSearch Kibana
    description: |
      Elastic Search Kibana
    iconClass: icon-elk-icon
    tags: "server,app"
  cloud: false

ansibleObjects: 

  - apiVersion: v1
    kind: ModelInjector
    metadata: 
      name: instance
      model: core.iaas
      anchor: r__elk_facts
      entrypoint: r__elk_facts.svc
      notify: ['elk']

    spec:
      # adhoc: false
      uniqueKeys:

        - name: uuid
          # value: bc31bdef-e6bb-4d3c-a81f-6bdb21224b16
          # value: d9da8125-3747-4e48-8743-acf80f90dd81
          yaqlRef: ahome_tags.ahome


      modelFields: 

        # - name: tags
        #   yaqlRef: ahome_tags.ahome
        #   fieldRef: inputs

        - name: elk
          yaqlRef: svc_url




fields:
  - name: elk_config_path
    label: Config url
    help_text: ElasticSearch LogStash & Kibana Config path 
    initial: https://gitlab.afahounko.com/community/elk
    required: true

  # - name: ec2_instance_type
  #   label: instance type
  #   help_text: ex. t2.micro
  #   initial: t2.micro
  #   type: select
  #   choices:
  #     - name: 1vCPU 0.5GiB RAM $0.0058/hr
  #       value: t2.nano

  #     - name: 1vCPU 1GiB RAM $0.0116/hr
  #       value: t2.micro

  #     - name: 1vCPU 1GiB RAM $0.023/hr
  #       value: t2.small
      
  #     - name: 2vCPUs 4GiB RAM $0.0464/hr
  #       value: t2.medium
      
  #     - name: 2vCPUs 8GiB RAM $0.0928/hr
  #       value: t2.large
      
  #     - name: 4vCPUs 16GiB RAM $0.1856/hr
  #       value: t2.xlarge
      
  #     - name: 8vCPUs 32GiB RAM $0.3712/hr
  #       value: t2.2xlarge



#   - name: ec2_instance_image
#     label: image
#     help_text: ex. ami-123456
#     initial: 309956199498;RHEL-8.0.*
#     # required: true
#     type: select
#     choices:
#       - name: RHEL 6 x64
#         value: 309956199498;RHEL-6*

#       - name: RHEL 7 x64
#         value: 309956199498;RHEL-7*

#       - name: RHEL 8 x64
#         value: 309956199498;RHEL-8.0.*


#   - name: ec2_wait
#     type: checkbox
#     advanced: true

#   - name: ec2_group
#     help_text: ex. webserver
#     advanced: true

#   - name: ec2_assign_public_ip
#     label: assign public ip
#     help_text: public ip
#     type: checkbox
#     advanced: true

#   - name: ec2_instance_count
#     label: count
#     type: integer
#     min_value: 1
#     max_value: 10
#     initial: 1
#     advanced: false


# credentials:
#   - name: username
#     label: username

#   - name: password
#     type: password
#     label: Password

#   - name: sshkey_name
#     advanced: true

#   - name: ec2_ssh_pubkey
#     label: ssh public key
#     advanced: true
#     type: textarea